#!/bin/bash -x

#Blocage de la communication entre deux VLANs différentes
sudo ip netns exec rout1 ip rule add from 192.168.100.0/24 to 192.168.200/24 prohibit
sudo ip netns exec rout1 ip rule add from 192.168.200.0/24 to 192.168.100/24 prohibit
sudo ip netns exec rout2 ip rule add from 192.168.200.0/24 to 192.168.100/24 prohibit
sudo ip netns exec rout2 ip rule add from 192.168.100.0/24 to 192.168.200/24 prohibit
