#!/bin/bash -x
#Partie de création des VLANS


#On supprime les adresses :

#R1
ip netns exec rout1 ip a del dev rout1-eth1 192.168.100.254/24
ip netns exec rout1 ip a del dev rout1-eth2 192.168.200.254/24
#R2
ip netns exec rout2 ip a del dev rout2-eth1 192.168.100.253/24
ip netns exec rout2 ip a del dev rout2-eth2 192.168.200.253/24
#Poste1
ip netns exec poste1 ip a del 192.168.100.1/24 dev poste1-eth0
#Poste2
ip netns exec poste2 ip a del 192.168.200.1/24 dev poste2-eth0
#Poste3
ip netns exec poste3 ip a del 192.168.100.2/24 dev poste3-eth0
#Poste4
ip netns exec poste4 ip a del 192.168.200.2/24 dev poste4-eth0


#Ajout des postes dans les VLANS adéquates

#Poste 1
ip netns exec poste1 ip link add link poste1-eth0 name poste1-eth0.100 type vlan id 100
ip netns exec poste1 ip a add dev poste1-eth0.100 192.168.100.1/24
ip netns exec poste1 ip link set dev poste1-eth0.100 up
#Poste 2
ip netns exec poste2 ip link add link poste2-eth0 name poste2-eth0.200 type vlan id 200
ip netns exec poste2 ip a add dev poste2-eth0.200 192.168.200.1/24
ip netns exec poste2 ip link set dev poste2-eth0.200 up
#Poste 3
ip netns exec poste3 ip link add link poste3-eth0 name poste3-eth0.100 type vlan id 100
ip netns exec poste3 ip a add dev poste3-eth0.100 192.168.100.2/24
ip netns exec poste3 ip link set dev poste3-eth0.100 up
#Poste 4
ip netns exec poste4 ip link add link poste4-eth0 name poste4-eth0.200 type vlan id 200
ip netns exec poste4 ip a add dev poste4-eth0.200 192.168.200.2/24
ip netns exec poste4 ip link set dev poste4-eth0.200 up

#On ajoute une route par defaut sur les postes 1 en prévision de la question sur l'acces a internet
sudo ip netns exec poste1 ip route add default via 192.168.100.254
sudo ip netns exec poste2 ip route add default via 192.168.200.254
sudo ip netns exec poste3 ip route add default via 192.168.100.254
sudo ip netns exec poste4 ip route add default via 192.168.200.254


